### ISSUE TITLE
[Unrelated request for ESRGAN] 

### ISSUE THREAD

**Issue by xpirad** [nihui/srmd-ncnn-vulkan#4]
Thanks for the work!
Can you consider implement ESRGAN in ncnn, please? お願い！
It seems like it's the State-of-the-art of super resolution and would be really really nice to have.

Anyway, thanks again!

**Comment by nihui** [comment]
In fact, I've implemented ESRGAN and found that the quality on noisy JPG image is very poor, so it's not released.

reference issue
https://github.com/xinntao/ESRGAN/issues/5
https://github.com/xinntao/ESRGAN/issues/19

**Comment by xpirad** [comment]
@nihui Please check out this page under section JPG compression
https://upscale.wiki/wiki/Model_Database
There are models trained specifically to remove jpeg compression artifacts.
For usage on jpegs, i suppose one can first de-artifact and then upscale. It's also mentioned in your link ESRGAN#5

**Comment by nihui** [comment]
In theory, it could produce better result with more specifically trained models and fine-grained hyper parameters settings.
However, it is a big trouble for normal users to figure out how to choose the proper model and settings.
It is even harder to play around with two models of different purpose, denoise and superresolution.

This project aims to provide a simple way to achieve image upscaling and denoising, so an end-to-end model is preferred.

**Comment by xpirad** [comment]
Well, it's not in theory. I've tried it and indeed it can produce better results. End-to-end doesn't always promise optimal quality. I suggest you try out JPG (80-100%) B for de-artifact and FireAlpha for SR using the fork over here https://github.com/BlueAmulet/ESRGAN
Maybe one can trade convenience for quality? After all, it is high quality photo that user would really want. And it's not that difficult, just run two models sequentially. 
Please do reconsider. @nihui

**Comment by WalkerMx** [comment]
@nihui This thread is dead, but it is the best place to ask.

How general was your implementation?  Could it accept different models?

If so, I'd have a proposition.  [My project](https://github.com/WalkerMx/AutoCrispy) also aims to make the process simple (I think you've seen it ^^; ).

Would you consider letting me test your ESRGAN implementation with my program?

Even if it wasn't quite 'end-to-end', I'm sure I could make the process completely seamless.

**Comment by nihui** [comment]
> @nihui This thread is dead, but it is the best place to ask.
> 
> How general was your implementation? Could it accept different models?
> 
> If so, I'd have a proposition. [My project](https://github.com/WalkerMx/AutoCrispy) also aims to make the process simple (I think you've seen it ^^; ).
> 
> Would you consider letting me test your ESRGAN implementation with my program?
> 
> Even if it wasn't quite 'end-to-end', I'm sure I could make the process completely seamless.

hello

In fact, the ReaSR model architecture is identical to the ESRGAN ones, you can assume it is yet another ESRGAN model
Thus, it is possible to convert most of the models here https://upscale.wiki/wiki/Model_Database to ncnn, and then use them with the realsr-ncnn-vulkan tool. I have converted some of them, and these ones work as expected.

However, as the model arch is identical, the runtime speed is identical too.
Because the RealSR produces much better result, I don't think it makes sense to use these ESRGAN models for general purposes.

But there are a few interesting models, such as jpeg-denoise, deblur, etc
If necessary, you can leave a message in realsr github issue

:smile:
