### ISSUE TITLE
关于srmd 模型param文件里的一个问题

### ISSUE THREAD

**Issue by huoshuai-dot** [nihui/srmd-ncnn-vulkan#8]
up ，srmd_x4.param 第一个conv的weight_data_size是21888 这个如果没有问题的话 那意味着输入图像的channel size是19？3*3*128*19=21888？那这个输入的预处理是怎么做成19通道的呢？

**Comment by nihui** [comment]
https://github.com/nihui/srmd-ncnn-vulkan/blob/master/src/srmd_preproc.comp

**Comment by huoshuai-dot** [comment]
> https://github.com/nihui/srmd-ncnn-vulkan/blob/master/src/srmd_preproc.comp

3q
