### ISSUE TITLE
vkEnumeratePhysicalDevices failed -3

### ISSUE THREAD

**Issue by Geneww** [nihui/srmd-ncnn-vulkan#9]
run with ubuntu18.04 error but my windows pc run success, Ubuntu Nvidia RTX2080TI*2 Driver Version: 460.56
vkEnumeratePhysicalDevices failed -3
invalid gpu device

**Comment by werdck** [comment]
What was your solution?

**Comment by jun214384468** [comment]
我也遇到了同样的问题

**Comment by luyi404** [comment]
Same problem.
